POST http://localhost:9090/reports
Content-Type: application/json

{
  "domainName": "love.com"
}


POST https://solid-forks-feel.loca.lt/reports
Content-Type: application/json

{
  "domainName": "love.com"
}