POST http://localhost:9090/reports
Content-Type: application/json

{
  "domainName": "facebook.org",
  "doesAllowAnalyzeContent": false,
  "isParkedDomain": true,
  "redirectsTo": "http://parked.mywebsite.org",
  "isKnownRegistrar": false,
  "isDnsBlackListed": true,
  "supportsHsts": false,
  "hasFavIcon": false,
  "domainAge": 3,
  "domainAgeReadable": false,
  "sslState": {
    "valid": false,
    "error": "SSL certificate expired"
  },
  "supportsCSP": false,
  "whoisHidden": true,
  "implementsReferrerPolicy": false,
  "loadsExternalObjects": false,
  "isAbnormalUrl": true,
  "urlTooLong": true,
  "isProtectedAgaintsClickJacking": false,
  "isUrlShortened": true,
  "doesSupportHSTS": false,
  "isProtectedAgainstXSS": false,
  "doesLoadExternalObjects": false
}

