POST http://localhost:9090/reports
Content-Type: application/json

{
  "domainInfo": {
    "domainName": "love.com",
    "doesAllowAnalyzeContent": false,
    "isParkedDomain": true,
    "redirectsTo": "http://parked.mywebsite.org",
    "isKnownRegistrar": true,
    "isDnsBlackListed": false,
    "supportsHsts": true,
    "hasFavIcon": false,
    "domainAge": 113340043880, 
    "domainAgeReadable": true,
    "sslState": {
      "valid": false,
      "error": "SSL certificate expired"
    },
    "supportsCSP": false,
    "whoisHidden": true,
    "implementsReferrerPolicy": false,
    "loadsExternalObjects": false,
    "isAbnormalUrl": true,
    "urlTooLong": true,
    "isProtectedAgaintsClickJacking": false,
    "isUrlShortened": true,
    "doesSupportHSTS": false,
    "isProtectedAgainstXSS": false,
    "doesLoadExternalObjects": true
  },
  "data": {
    "any": "any"
  }
}

