export const BASE_SCORE = 50; // default trust_ score of url out of 100
export enum PROPERTY_SCORE_WEIGHTAGE {
  GOOGLE_SAFE_BROWSING = 0.9,
  DOMAIN_RANK = 0.9,
  SSL_VALID = 0.4,
  DOMAIN_AGE = 0.4,
  DOMAINE_PARKED = 0.4,
  IS_URL_SHORTENED = 0.8,
  HSTS_SUPPORT = 0.1,
  IP_PRESENT = 0.8,
  URL_REDIRECTS = 0.1,
  TOO_LONG_URL = 0.1,
  TOO_DEEP_URL = 0.5,
  CONTENT = 0.1,
  HAS_FAV_ICON = 0.1,
  URL_HAS_ALT_SIGN = 0.1,
  URL_LOADS_EXTERNAL_OBJECTS = 0.2,
  DNS_BLACK_LISTED = 0.3,
}

export enum HIGHLIGHT_LABELS_NEGATIVE {
  REGISTRAR_UNKNOWN = "Domain registrar unknown",
  URL_SHORTENED = "URL is shortened",
  DOES_NOT_SUPPORT_HSTS = "Website does not supports HTTP Strict Transport Security (HSTS) policy",
  IP_PRESENT = "Website uses an IP address instead of a domain name.",
  URL_TOO_LONG = "URL is too long!",
  URL_TOO_DEEP = "URL is too deep",
  HAS_NO_ICON = "Website has no icon",
  URL_SUSP_CHARS = "Url contains some characters that are common in malicious links.",
  LOADS_EXTERNAL_OBJECTS = "Website loads external objects",
  DOES_NOT_IMPLEMENT_REFERER_POLICY = "Website doesn not control how much information is shared through the HTTP Referer header.",
  NOT_PROTECTED_AGAINST_INJECTION = "Website is not protected against cross-site scripting, clickjacking and other code injection attacks.",
  URL_REDIRECTS = "URL redirects to another address.",
  DOES_HIDE_WHOIS = "The owner of the website is using a service to hide their identity on WHOIS",
  DOMAIN_PARKED = "Domain is Parked",
  URL_ABNORMAL = "URL seems abnormal",
  DOES_NOT_ALLOW_ANALYSE_CONTENT = "The site does not allow us to analyze its content",
  DOMAIN_AGE_VERY_YOUNG = "This website is (very) young.",
  // DOES_NOT_ALLOW_ANALYSE_CONTENT = "We could not analyze the content of the site",
  DNS_BLACK_LISTED = "Server IP address has been listed in one or more DNS Black lists",
  NO_SSL_CERT_FOUND = "We did not find a valid SSL certificate",
}

export enum HIGHLIGHT_LABELS_POSITIVE {
  SSL_VALID = "The SSL certificate is valid",
  MAINLY_REVIEWED_POSITIVELY = "This website has been reviewed mainly positively",
  SAFE_BY_GOOGLE_SAFE_BROWSING = "This website is considered safe by Google Safe Browsing",
  SAFE_DNS_FILTER = "DNS Filter labels this site as safe",
  RANKED_AMONG_TOP_1OOK = "Domain ranked among the top 100K globally",
  RANKED_AMONG_TOP_5OOK = "Domain ranked among the top 500K globally",
  REGISTRAR_GOOD_REPUTATION = "The registrar of this domain enjoys a good reputation",
  URL_NOT_SHORTENED = "URL is not shortened",
  SUPPORTS_HSTS = "Website supports HTTP Strict Transport Security (HSTS) policy",
  IMPLEMENTS_REFERER_POLICY = "Website implements a policy which protects data from being leaked to insecure origins.",
  PROTECTED_AGAINST_INJECTION = "Website is protected against cross-site scripting, clickjacking and other code injection attacks.",
  NOT_DNS_BLACKLISTED = "Review nav DNSBL lookup confirms that the domain name has not been reported",
  DOMAIN_AGE_SOME_YEARS = "This website has existed for quite some years",
  DOMAIN_AGE_OLD = "This website is (very) old",
}
